FROM node:20-alpine as test

WORKDIR /usr/src/app

RUN npm install -g pnpm

COPY package*.json pnpm-lock.yaml tsconfig.json ./

ENV NODE_ENV=TEST

RUN pnpm install --frozen-lockfile

COPY ./ ./

RUN pnpm run prebuild
RUN pnpm run build

CMD [ "pnpm", "run", "test" ]


