import { HttpStatus } from '@nestjs/common';
import { ERROR } from '.';

export namespace EMS_EMPLOYEE_ERROR {
  export type EMPLOYEE_MULTIPLE_ALREADY_EXIST = ERROR<'EMPLOYEE_MULTIPLE_ALREADY_EXIST', HttpStatus.BAD_REQUEST>;
  export type EMPLOYEE_NOT_FOUND = ERROR<'EMPLOYEE_NOT_FOUND', HttpStatus.NOT_FOUND>;
  export type EMPLOYEE_PASSWORD_SAME = ERROR<'EMPLOYEE_PASSWORD_SAME', HttpStatus.BAD_REQUEST>;
  export type EMPLOYEE_PASSWORD_INVALID = ERROR<'EMPLOYEE_PASSWORD_INVALID', HttpStatus.BAD_REQUEST>;
}
